# Generated by Django 2.0.5 on 2018-05-31 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('host_id', models.CharField(editable=False, max_length=64, verbose_name='创建人id')),
                ('member', models.ManyToManyField(related_name='成员', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
