# Generated by Django 2.0.5 on 2018-05-29 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('creat_time', models.DateTimeField(verbose_name='创建时间')),
                ('event', models.ForeignKey(on_delete='活动', to='event.Event')),
                ('host', models.OneToOneField(on_delete='创始人', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='GroupEventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete='活动', to='event.Event')),
                ('group', models.ForeignKey(on_delete='群组', to='group.Group')),
                ('user', models.ForeignKey(on_delete='用户', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_event_user',
            },
        ),
    ]
