# Generated by Django 2.0.5 on 2018-05-31 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('member', models.IntegerField(verbose_name='参加人数')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='活动地址')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('start_time', models.DateTimeField(verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(verbose_name='活动结束时间')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete='群组', to='group.Group')),
                ('organizer', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='组织者')),
            ],
            options={
                'db_table': 'event_details',
            },
        ),
        migrations.CreateModel(
            name='GroupEventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete='活动', to='event.Event')),
                ('group', models.ForeignKey(on_delete='群组', to='group.Group')),
                ('user', models.ForeignKey(on_delete='用户', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_event_user',
            },
        ),
    ]
