# Generated by Django 2.0.5 on 2018-05-29 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('member', models.IntegerField(verbose_name='参加人数')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('time', models.DateTimeField(verbose_name='活动开始时间')),
                ('creat_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('organizer', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='组织者')),
            ],
            options={
                'db_table': 'event_details',
            },
        ),
    ]
